var app = document.getElementById('para');

var Typewriter = new Typewriter(para, {
    loop: true,
    delay: 50,
});


Typewriter
    .typeString('Utilizing coding languages such as <strong><span style="color:#F0DB4F">Pyt</span><span style="color:blue">hon</span></strong>.') 
    .pauseFor(2000)
    .deleteChars(7)
    .typeString('<strong><span style="color:#F0DB4F">JavaScript</span></strong>.')
    .pauseFor(2000)
    .deleteChars(11)
    .typeString('<strong><span style="color:#e34c26">HTML</span></strong>.')
    .pauseFor(2000)
    .deleteChars(5)
    .typeString('<strong><span style="color:#264de4">CSS</span></strong>.')
    .pauseFor(2000)
    .deleteChars(4)
    .typeString('<strong><span style="color:#F0DB4F">Pyt</span><span style="color:blue">hon</span></strong>.')
    .pauseFor(2000)
    .deleteChars(7)
    .typeString('<strong><span style="color:#F0DB4F">JavaScript</span></strong>.')
    .pauseFor(2000)
    .deleteChars(11)
    .typeString('<strong><span style="color:#e34c26">HTML</span></strong>.')
    .pauseFor(2000)
    .deleteChars(5)
    .typeString('<strong><span style="color:#264de4">CSS</span></strong>.')
    .pauseFor(2000)
    .deleteChars(4)
    .typeString('<strong><span style="color:#F0DB4F">Pyt</span><span style="color:blue">hon</span></strong>.')
    .pauseFor(2000)
    .deleteChars(7)
    .typeString('<strong><span style="color:#F0DB4F">JavaScript</span></strong>.')
    .pauseFor(2000)
    .deleteChars(11)
    .typeString('<strong><span style="color:#e34c26">HTML</span></strong>.')
    .pauseFor(2000)
    .deleteChars(5)
    .typeString('<strong><span style="color:#264de4">CSS</span></strong>.')
    .pauseFor(2000)
    .deleteChars(4)
    .typeString('<strong><span style="color:#F0DB4F">Pyt</span><span style="color:blue">hon</span></strong>.')
    .pauseFor(2000)
    .deleteChars(7)
    .typeString('<strong><span style="color:#F0DB4F">JavaScript</span></strong>.')
    .pauseFor(2000)
    .deleteChars(11)
    .typeString('<strong><span style="color:#e34c26">HTML</span></strong>.')
    .pauseFor(2000)
    .deleteChars(5)
    .typeString('<strong><span style="color:#264de4">CSS</span></strong>.')
    .pauseFor(2000)
    .deleteChars(4)
    .typeString('<strong><span style="color:#F0DB4F">Pyt</span><span style="color:blue">hon</span></strong>.')
    .pauseFor(2000)
    .deleteChars(7)
    .typeString('<strong><span style="color:#F0DB4F">JavaScript</span></strong>.')
    .pauseFor(2000)
    .deleteChars(11)
    .typeString('<strong><span style="color:#e34c26">HTML</span></strong>.')
    .pauseFor(2000)
    .deleteChars(5)
    .typeString('<strong><span style="color:#264de4">CSS</span></strong>.')
    .pauseFor(2000)
    .deleteChars(4)
    .typeString('<strong><span style="color:#F0DB4F">Pyt</span><span style="color:blue">hon</span></strong>.')
    .pauseFor(2000)
    .deleteChars(7)
    .typeString('<strong><span style="color:#F0DB4F">JavaScript</span></strong>.')
    .pauseFor(2000)
    .deleteChars(11)
    .typeString('<strong><span style="color:#e34c26">HTML</span></strong>.')
    .pauseFor(2000)
    .deleteChars(5)
    .typeString('<strong><span style="color:#264de4">CSS</span></strong>.')
    .pauseFor(2000)
    .deleteChars(4)
    .start();


